# This service is used to call minimum-time trajectories starting from rest and finishing at rest
# corridor_width imposes corridor contraints between every two waypoints
geometry_msgs/Point[] pos_array
float32 corridor_width
float32 max_vel
float32 max_acc
float32 max_jerk
---
p4_ros/PolyPVA[] X
p4_ros/PolyPVA[] Y
p4_ros/PolyPVA[] Z
std_msgs/Float32 cost